Inventory: main.o Inventory.o AddItem.o Item.o
	g++ main.o Inventory.o AddItem.o Item.o -o Inventory

main.o:main.cpp
	g++ -c main.cpp
Inventory.o:Inventory.cpp
	g++ -c Inventory.cpp
AddItem.o:AddItem.cpp
	g++ -c AddItem.cpp
Item.o:Item.cpp
	g++ -c Item.cpp
